#! /usr/bin/python3

import os
import json
import shutil

script_dir = os.path.abspath(__file__)
configure_path = os.path.join(os.path.dirname(script_dir), "configure.json")

configure_file = open(configure_path)
configure = json.load(configure_file)['link-cache']
configure_file.close()

print('[-] link cache')
for target_root in configure['targets']:
    src_root = os.path.join(configure['home'], target_root)
    dst_root = os.path.join(configure['link-root'], target_root)
    
    print(f'[-] link from {src_root}')

    if not os.path.exists(dst_root):
        os.makedirs(dst_root)

    if os.path.exists(src_root):
        if os.path.islink(src_root):
            continue
        if os.listdir(src_root):
            shutil.rmtree(dst_root)
            shutil.move(src_root, dst_root)
        else:
            shutil.rmtree(src_root)

    os.symlink(dst_root, src_root)
