#! /usr/bin/python3

from genericpath import exists
import os
import json
import shutil

script_dir = os.path.abspath(__file__)
configure_path = os.path.join(os.path.dirname(script_dir), "configure.json")

configure_file = open(configure_path)
configure = json.load(configure_file)['link-cache']
configure_file.close()

print('[-] link cache')
for target_root in configure['targets']:
    src_root = os.path.join(configure['home'], target_root)
    dst_root = os.path.join(configure['link-root'], target_root)
    print(f'[-] link from {src_root}')
    if not os.path.exists(os.path.dirname(dst_root)):
        os.makedirs(dst_root)
    shutil.move(src_root, dst_root)
    os.symlink(dst_root, src_root)