#! /bin/bash

HERE=$(dirname $0)

for EXT in $(cat $HERE/vscode-extensions); do
    code --install-extension "$EXT"
done

cp $HERE/vscode-settings $VSCODE_HOME/code-portable-data/user-data/User/settings.json

exit 0
